### ISSUE TITLE
Add multiple widget on screen and random gradient background everyday

### ISSUE THREAD

**Issue by baarbarik** [BirjuVachhani/pluto#4]
- currently we can add only one widget at a time but it would be great if we can set stacked widget like clocks, to-do lists, timer. 

- also set random gradient background everyday so don't need to set it everyday or frequently

**Comment by BirjuVachhani** [comment]
> also set random gradient background everyday so don't need to set it everyday or frequently.

This is available in the latest release v0.4.0.

**Comment by BirjuVachhani** [comment]
> Currently we can add only one widget at a time but it would be great if we can set stacked widget like clocks, to-do lists, timer.

This has been on my radar for a while. However I am not sure about this feature. The theme and appeal of this extension is minimal and clean. Having multiple widgets around might affect that!

I am closing this issue and opening a separate issue for this. Feel free to upvote if you really want this feature. I may reconsider implementing it if enough people wants it.

Thanks.
