### ISSUE TITLE
Feature : Add only date as well as date-time section in Widget

### ISSUE THREAD

**Issue by Priyammm05** [BirjuVachhani/pluto#6]
**Issue Description:**
Currently, the Pluto project only supports time values, but lacks support for date and combined date-time values. This feature would be highly beneficial for users who require more comprehensive date and time functionality.

**Proposed Solution:**
To enhance the project's capabilities, we should add support for date values, time values, and the ability to work with combined date-time values. This will provide users with greater flexibility and utility when working with temporal data.

**Comment by Priyammm05** [comment]
Please assign it to me @BirjuVachhani

**Comment by BirjuVachhani** [comment]
Good luck @Priyammm05

**Comment by Priyammm05** [comment]
Thanks I will start working on it.
